version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    networks:
      - net
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    env_file:
      - ./frontend.env
    entrypoint: sh /tmp/frontend_entry.sh

networks:
  net:
    driver: bridge
